[package]
name = "blockchain-auth"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ed25519-dalek.workspace = true
bs58.workspace = true
thiserror.workspace = true
rand.workspace = true
base64.workspace = true

