apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-api-config
data:
  APP__ENV: "stage"
  APP__SERVICE__NAME: "blockchain-api"
  APP__SERVICE__VERSION: "0.2.0"
  APP__SERVER__HOST: "0.0.0.0"
  APP__SERVER__PORT: "8080"
  APP__SERVER__TLS_ENABLED: "false"
  APP__SERVER__REQUEST_BODY_LIMIT_BYTES: "1048576"
  APP__TELEMETRY__LOG_FORMAT: "json"
  APP__TELEMETRY__LOG_LEVEL: "info"
  APP__TELEMETRY__REQUEST_ID_HEADER: "x-request-id"
  APP__INTEGRATIONS__ENABLE_POSTGRES: "true"
  APP__INTEGRATIONS__ENABLE_REDIS: "true"
  APP__INTEGRATIONS__ENABLE_KAFKA: "true"
  APP__INTEGRATIONS__PG_MAX_CONNECTIONS: "10"
  APP__INTEGRATIONS__PG_CONNECT_TIMEOUT_MS: "3000"
  APP__INTEGRATIONS__PG_IDLE_TIMEOUT_MS: "300000"
  APP__INTEGRATIONS__REDIS_CONNECT_TIMEOUT_MS: "1000"
  APP__INTEGRATIONS__REDIS_COMMAND_TIMEOUT_MS: "1000"
  APP__INTEGRATIONS__KAFKA_CLIENT_ID: "blockchain-api"
  APP__INTEGRATIONS__KAFKA_METADATA_TIMEOUT_MS: "1500"
  APP__AUTH__ENABLED: "true"
  APP__AUTH__NONCE_TTL_SECONDS: "300"
  APP__AUTH__NONCE_CLEANUP_INTERVAL_SECONDS: "60"
  APP__RATE_LIMIT__ENABLED: "true"
  APP__RATE_LIMIT__WINDOW_SIZE_SECONDS: "60"
  APP__RATE_LIMIT__MAX_REQUESTS_PER_WINDOW: "100"
  APP__RATE_LIMIT__BYPASS_PATHS: '["/healthz", "/readyz", "/version", "/metrics"]'
  APP__WAF__ENABLED: "true"
  APP__WAF__MODE: "monitor"
  APP__WAF__SCORE_THRESHOLD: "100"
  APP__WAF__BAN_DURATION_SECONDS: "3600"
  APP__WAF__BYPASS_PATHS: '["/healthz", "/readyz", "/version", "/metrics"]'
  APP__CACHE__BACKEND: "redis"
  APP__CACHE__MAX_ENTRIES: "10000"
  APP__CACHE__TTL_SECONDS: "300"
  APP__WS__ENABLED: "true"
  APP__WS__PATH: "/ws"
  APP__WS__MAX_CONNECTIONS: "1000"
  APP__WS__PING_INTERVAL_SECONDS: "30"
  APP__WS__PING_TIMEOUT_SECONDS: "10"
  APP__KAFKA__ENABLED: "true"
  APP__KAFKA__TOPIC: "transactions"
  APP__KAFKA__BATCH_SIZE: "100"
  APP__KAFKA__BATCH_TIMEOUT_MS: "1000"
  APP__KAFKA__DLQ_TOPIC: "transactions-dlq"
  APP__KAFKA__DLQ_ENABLED: "true"
  APP__METRICS__ENABLED: "true"
  APP__METRICS__PROMETHEUS_ENABLED: "true"
  APP__METRICS__PROMETHEUS_BIND: "0.0.0.0:9464"
  APP__METRICS__HTTP_REQUEST_LABELS: '["method", "path", "status"]'
  APP__METRICS__WS_LABELS: '["event", "ok"]'
  APP__METRICS__CACHE_LABELS: '["backend", "op", "hit"]'
  APP__OTEL__ENABLED: "true"
  APP__OTEL__SERVICE_NAME: "blockchain-api"
  APP__OTEL__SERVICE_NAMESPACE: "pumpnex"
  APP__OTEL__SERVICE_VERSION: "0.2.0"
  APP__OTEL__RESOURCE_ATTRIBUTES: '{"deployment.environment": "stage"}'
  APP__OTEL__TRACES__EXPORTER: "otlp"
  APP__OTEL__TRACES__OTLP_ENDPOINT: "http://127.0.0.1:4317"
  APP__OTEL__TRACES__PROTOCOL: "grpc"
  APP__OTEL__TRACES__SAMPLE_RATIO: "0.1"
  APP__OTEL__TRACES__INCLUDE_INTERNAL: "true"
  APP__OTEL__METRICS__EXPORTER: "prometheus"
  APP__OTEL__METRICS__PROMETHEUS_BIND: "0.0.0.0:9464"
  APP__OTEL__METRICS__OTLP_ENDPOINT: "http://127.0.0.1:4317"
  APP__OTEL__LOGS__INJECT_TRACE_IDS: "true"
  APP__SENTRY__ENABLED: "false"
  APP__SENTRY__ENVIRONMENT: "stage"
  APP__SENTRY__RELEASE: "blockchain-api@0.2.0"
  APP__SENTRY__TRACES_SAMPLE_RATE: "0.0"
  APP__SECURITY__CORS_ALLOWED_ORIGINS: '["https://stage.example.com"]'
  APP__SECURITY__CORS_ALLOWED_METHODS: '["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]'
  APP__SECURITY__CORS_ALLOWED_HEADERS: '["content-type", "authorization", "x-request-id"]'
  APP__SECURITY__HSTS_ENABLED: "true"
  APP__SECURITY__HSTS_MAX_AGE_SECS: "31536000"
  APP__SECURITY__FRAME_OPTIONS: "DENY"
  APP__SECURITY__REFERRER_POLICY: "no-referrer"
  APP__SECURITY__X_CONTENT_TYPE_OPTIONS: "nosniff"
  APP__SECURITY__PERMISSIONS_POLICY: "geolocation=(), microphone=(), camera=()"
  APP__SECURITY__CSP_ENABLED: "true"
  APP__SECURITY__CSP: "default-src 'none'; frame-ancestors 'none';"
  APP__TLS__ENABLED: "false"
  APP__TLS__CERT_PATH: "/etc/blockchain-api/tls/cert.pem"
  APP__TLS__KEY_PATH: "/etc/blockchain-api/tls/key.pem"
  APP__DB__RUN_MIGRATIONS_ON_START: "true"
  APP__DEPLOY__SERVICE_HTTP_PORT: "8080"
  APP__DEPLOY__METRICS_PORT: "9464"
  APP__DEPLOY__GRACEFUL_SHUTDOWN_SECS: "10"
  APP__IMAGE__NAME: "ghcr.io/OWNER/blockchain-api"

