apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- secret.yaml
- hpa.yaml

commonLabels:
  app: blockchain-api
  version: v0.2.0

patches:
- target:
    kind: Deployment
    name: blockchain-api
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ghcr.io/OWNER/blockchain-api:latest
